= Backend: API server

* API documentation is available at http://localhost:4000/api/docs
* OpenAPI API definition file is available at http://localhost:4000/api/swagger.json


== Framework

Backend uses the framework https://github.com/lukeautry/tsoa[TSOA] for the REST API.
It is based on :

* https://expressjs.com/[express.js] for the web server
* https://swagger.io/[Swagger] for the API live documentation
* https://www.typescriptlang.org/[Typescript]

== Code structure

Code is splitted in 2 main folders :

* *controllers* for the API endpoint
* *services* to manage interactions with others systems (like elasticsearch)

There are also 2 importants files

* *index.ts :* it's the starting point of the application
* *error-handler.ts :* Centralized all the error for the API

IMPORTANT: File `routes.ts` must not be edited, it is generated by the framework TSOA

== Changing the data model

If the data model changes, you need to :

* Check the typescript definition `ArchiveElectoralCandidat` &  `ArchiveElectoralItem` in the file `./src/services/import.ts`
* Check the method `Import.postProcessItem` that cast an IA item to ES item in the file  `./src/services/import.ts`
* Check the ES index mapping stored in the key `config.elastic_index_configuration` in the file `./src/config/index`
* Check the functions `archiveElectoralItemToCsvLine` & `archiveElectoralCandidatToArrayFields` in `./src/utils` that help to generate the CSV
* Check the constant `ArchiveElectoralItemCsvHeader` in `./src/utils` that is the CSV header

Then, you can see the impact in the frontend application, by generating the new types and see the compilation errors :

[source,bash]
----
$> cd backend
$> # build the routes and so the exported types
$> npm run build
$> # backend server must be running to generate frontend types
$> npm start
$> cd ../frontend
$> npm run generate:types
$> npm run start
----

== API Documentation

The API is self-documented thanks to TSOA and the OpenAPI specification and is accessible at http://localhost/api/docs

== How to import data

To import data, you just need to run this command :

[source,bach]
----
curl -X 'POST' 'http://localhost/api/v1/import'
----

The first time you run this command, it will do a full import.
The other times, it will do a delta-import, based on the last import date that is stored in the the file `.last_import.txt`

NOTE: The API always returns a HTTP code 2XX, even if the import has errors. In this case the HTTP code is a **206**.
To know the detail of the process, this endpoint returns a report. Please check the documentation at http://localhost/api/docs/#/Import/Import

IMPORTANT: If you want to reset the index, just delete the file `.last_import.txt` and run the command `curl -X 'POST' 'http://localhost/api/v1/import'`.
The behind ES index will be replaced by the new one at the end of the process, so it doesn't impact the application.
