import { SearchTypeDefinition } from "../types";

// Default configuration file
export const professionSearch: SearchTypeDefinition = {
  queryType: "profession",
  index: "",
  label: "Profession de foi",
  sorts: [
    {
      label: "Chronologique",
      expression: [
        "date",
        { "departement.raw": "asc" },
        { "circonscription.raw": "asc" },
        "candidats.nom.raw",
        "contexte-tour.raw",
      ],
      default: true,
    },
  ],
  filtersGroups: [
    {
      label: "Élection",
      openByDefault: true,
      filters: [
        {
          id: "annee",
          field: "annee",
          type: "terms",
          label: "Année",
          isMulti: true,
          order: "key_asc",
        },
        {
          id: "contexte-election",
          field: "contexte-election",
          type: "terms",
          label: "Type",
          isMulti: true,
          order: "key_asc",
          wildcardSearch: false,
        },
        {
          id: "contexte-tour",
          field: "contexte-tour",
          type: "terms",
          label: "Tour",
          isMulti: true,
          order: "key_asc",
          wildcardSearch: false,
        },
      ],
    },
    {
      label: "Circonscription",
      openByDefault: true,
      filters: [
        {
          id: "departement-insee",
          field: "departement-insee",
          type: "terms",
          label: "Département",
          isMulti: true,
          order: "key_asc",
          wildcardSearch: false,
        },
        {
          id: "circonscription",
          field: "circonscription",
          type: "terms",
          label: "Numéro",
          isMulti: true,
          order: "key_asc",
          wildcardSearch: false,
        },
      ],
    },
    {
      label: "Groupe politique",
      filters: [
        {
          id: "candidats.liste",
          field: "candidats.liste",
          type: "terms",
          label: "Liste",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.soutien",
          field: "candidats.soutien",
          type: "terms",
          label: "Organisation",
          isMulti: true,
          order: "count_desc",
        },
      ],
    },
    {
      label: "Candidat⋅e suppléant⋅e",
      filters: [
        {
          id: "suppleant.sexe",
          field: "candidats.sexe",
          extraQueryField: { term: { "candidats.type.raw": "suppléant" } },
          type: "terms",
          label: "Sexe",
          isMulti: true,
          order: "count_desc",
        },
      ],
    },
    {
      label: "Candidat⋅e titulair⋅e",
      filters: [
        {
          id: "titulaire.sexe",
          field: "candidats.sexe",
          extraQueryField: { term: { "candidats.type.raw": "titulaire" } },
          type: "terms",
          label: "Sexe",
          isMulti: true,
          order: "count_desc",
        },
      ],
    },
    {
      label: "Candidat⋅e",
      filters: [
        {
          id: "candidats.prenom-nom",
          field: "candidats.prenom-nom",
          type: "terms",
          label: "Prénom Nom",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.nom",
          field: "candidats.nom",
          type: "terms",
          label: "Nom",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.prenom",
          field: "candidats.prenom",
          type: "terms",
          label: "Prénom",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.sexe",
          field: "candidats.sexe",
          type: "terms",
          label: "Sexe",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.age-tranche",
          field: "candidats.age-tranche",
          type: "terms",
          label: "Tranche d'âge",
          isMulti: true,
          order: "count_desc",
        },
      ],
    },
    {
      label: "Activités candidat⋅e",
      filters: [
        {
          id: "candidats.profession",
          field: "candidats.profession",
          type: "terms",
          label: "Profession",
          isMulti: true,
          wildcardSearch: true,
          order: "count_desc",
        },
        {
          id: "candidats.mandat-en-cours",
          field: "candidats.mandat-en-cours",
          type: "terms",
          label: "Mandat en cours",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.mandat-passe",
          field: "candidats.mandat-passe",
          type: "terms",
          label: "Mandat passé",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.associations",
          field: "candidats.associations",
          type: "terms",
          label: "Association",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.autres-statuts",
          field: "candidats.autres-statuts",
          type: "terms",
          label: "Autre statut",
          isMulti: true,
          order: "count_desc",
        },
        {
          id: "candidats.decorations",
          field: "candidats.decorations",
          type: "terms",
          label: "Décoration",
          isMulti: true,
          order: "count_desc",
          wildcardSearch: false,
        },
      ],
    },
    {
      label: "Contenu",
      filters: [
        {
          id: "ocr",
          type: "query",
          label: "Transcription (OCR)",
        },
      ],
    },
  ],
};
